name: CI

on:
  push

jobs:
  Test:
    name: Test and TSC check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: ['lts/*']
        os: [windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'
      - name: Install
        run: pnpm install
      - name: Test
        run: pnpm build
      - name: cat index.js
        run: cat dist/index.js
